<?php

/*
|--------------------------------------------------------------------------
| Configuration for the workbench demo application
|--------------------------------------------------------------------------
|
| Served by `php vendor/bin/testbench serve`. It is the package's own config with a
| handful of overrides, read from the real file rather than restated here so it cannot
| drift — and so this file shows only what the demo changes.
|
| Built from the whole array rather than the overrides alone because `mergeConfigFrom()`
| merges at the top level only: a file returning `['service_worker' => ['enabled' => true]]`
| would replace the entire `service_worker` block, defaults included, and leave the demo
| running on a configuration no application would ever have.
|
*/

$config = require __DIR__ . '/../../config/pwax.php';

// The demo exists to be looked at in a browser, and the worker's failure modes are only
// visible in one.
$config['service_worker']['enabled'] = true;

$config['head']['title_template'] = ':title · Pwax';
$config['head']['image'] = '/img/og.png';

$config['manifest']['name'] = 'Pwax Demo';
$config['manifest']['short_name'] = 'Pwax';
$config['manifest']['description'] = 'A demo application for working on the package.';

// The JSON catalog the `/sample` page's document renders against. Two shapes on purpose:
// `Card` in the short form, which infers everything, and the other two spelled out — which
// is what a document generated by a model needs, and what `pwax:catalog`-shaped tooling
// would read.
$config['json']['components'] = [
    'Card' => "@pwaxImport('components.card')",

    'Button' => [
        'component' => "@pwaxImport('components.button')",
        'description' => 'A clickable button that emits a "press" event.',
        'props' => [
            'label' => ['type' => 'string', 'required' => true],
            'variant' => ['type' => 'enum', 'values' => ['primary', 'secondary']],
        ],
    ],

    'Text' => [
        'component' => "@pwaxImport('components.text')",
        'description' => 'A line of text, for whatever an expression resolved to.',
        'props' => [
            'value' => ['type' => 'any'],
            'tone' => ['type' => 'enum', 'values' => ['quiet', 'loud']],
        ],
    ],

    'Field' => [
        'component' => "@pwaxImport('components.field')",
        'description' => 'A labelled text input, for a prop bound with $bindState.',
        'props' => [
            'label' => ['type' => 'string'],
            'modelValue' => ['type' => 'string'],
        ],
    ],

    // Renders a prop as a URL, which is the sink `/hostile` checks.
    'Link' => [
        'component' => "@pwaxImport('components.link')",
        'description' => 'A link to somewhere in the application.',
        'props' => [
            'href' => ['type' => 'string', 'required' => true],
            'label' => ['type' => 'string'],
        ],
    ],
];

// A component that is not a Pwax component: `workbench/public/js/demo-lib.js` puts it
// on `window`, and the catalog reaches it by dotted path. `events` is needed because a
// global has no options the runtime can read `emits` from.
$config['scripts'] = [
    ['src' => '/js/demo-lib.js', 'head' => true],
];

$config['json']['components']['Stamp'] = [
    'component' => 'DemoLib.Stamp',
    'description' => 'A button from a library the application already loads.',
    'events' => ['stamped'],
    'props' => ['label' => ['type' => 'string', 'required' => true]],
];

// The one action on `/vocabulary` that needs a handler. Everything else in that
// document is either a renderer action or one Pwax supplies.
$config['json']['actions'] = [
    'save' => "@pwaxImport('actions.save')",
    // Rejects on purpose, so the document's `onError` has something to react to.
    'explode' => "@pwaxImport('actions.explode')",
];

// A stable identity, so the demo is not reinstalled as a second app whenever `start_url`
// is edited — which is the whole reason `pwax:doctor` asks for one.
$config['manifest']['id'] = '/';

// Solid squares from `workbench/public/img`, generated rather than designed. They are here
// so the demo is actually installable: without a 192 and a 512 no browser offers to install
// it, and the one claim hardest to check by reading code is the one about being installable.
$config['manifest']['icons'] = [
    ['src' => '/img/icon-192.png', 'sizes' => '192x192', 'type' => 'image/png', 'purpose' => 'any'],
    ['src' => '/img/icon-512.png', 'sizes' => '512x512', 'type' => 'image/png', 'purpose' => 'any'],
    ['src' => '/img/icon-512.png', 'sizes' => '512x512', 'type' => 'image/png', 'purpose' => 'maskable'],
];

return $config;
