<?php

namespace Mxent\Pwax\Tests\Feature;

use Mxent\Pwax\Facades\Pwax;
use Mxent\Pwax\Support\Shell;
use Mxent\Pwax\Tests\TestCase;

/**
 * The JSON catalog, from `config/pwax.php` to the runtime configuration island.
 *
 * A catalog entry is the only thing standing between a generated document and the
 * application's components, so what the server resolves has to be exactly what was
 * configured — no more, and nothing lost on the way. The two config shapes are the point
 * of most of this: the short form is what someone writes first, the long form is what a
 * document generated by a model is validated against, and both have to arrive as the
 * same `{type, url, export}` the `vue.*` groups already produce.
 */
class JsonCatalogTest extends TestCase
{
    protected function defineEnvironment($app): void
    {
        parent::defineEnvironment($app);

        $app['config']->set('pwax.json.components', [
            'Card' => "@pwaxImport('components.badge')",
            'Modal' => 'module:components.modal',
            'Named' => "@pwaxImport('Backdrop from components.modal')",
            'Chart' => 'MyCharts.Line',
            'Button' => [
                'component' => "@pwaxImport('components.badge')",
                'description' => 'A button',
                'slots' => [],
                'props' => ['label' => ['type' => 'string', 'required' => true]],
            ],
            'Broken' => ['description' => 'names no component'],
        ]);

        $app['config']->set('pwax.json.actions', [
            'save' => "@pwaxImport('components.badge')",
        ]);
    }

    private function catalog(): array
    {
        return $this->app->make(Shell::class)->runtimeConfig()['json']['components'];
    }

    public function test_a_bare_reference_resolves_to_the_components_module_url(): void
    {
        $this->assertSame(
            ['type' => 'module', 'url' => Pwax::url('components.badge'), 'export' => ''],
            $this->catalog()['Card'],
            'The short config form must produce the same module entry the vue.* groups do, '
            . 'or the runtime has two shapes of catalog entry to understand instead of one.'
        );
    }

    public function test_the_module_prefix_is_accepted_as_well_as_the_directive(): void
    {
        $this->assertSame(Pwax::url('components.modal'), $this->catalog()['Modal']['url']);
    }

    public function test_a_named_export_is_carried_through(): void
    {
        $this->assertSame(
            ['type' => 'module', 'url' => Pwax::url('components.modal'), 'export' => 'Backdrop'],
            $this->catalog()['Named'],
            'Without the export name the runtime imports the module\'s default, which for a '
            . 'component published as a named export is not a component at all.'
        );
    }

    public function test_anything_that_is_not_a_component_reference_is_a_path_on_window(): void
    {
        $this->assertSame(
            ['type' => 'global', 'path' => 'MyCharts.Line'],
            $this->catalog()['Chart']
        );
    }

    public function test_the_long_form_keeps_the_reference_and_the_description_together(): void
    {
        $this->assertSame(
            [
                'type' => 'module',
                'url' => Pwax::url('components.badge'),
                'export' => '',
                'description' => 'A button',
                'slots' => [],
                'props' => ['label' => ['type' => 'string', 'required' => true]],
            ],
            $this->catalog()['Button'],
            'The description and prop types are what constrain a generated document. '
            . 'Dropping them here turns a validated catalog into a list of names.'
        );
    }

    public function test_an_entry_naming_no_component_is_left_out_rather_than_half_resolved(): void
    {
        $this->assertArrayNotHasKey(
            'Broken',
            $this->catalog(),
            'An entry with props and no component would reach the browser as a catalog name '
            . 'that resolves to nothing, and a document naming it would render an empty node.'
        );
    }

    public function test_actions_resolve_the_same_way_client_middleware_does(): void
    {
        $this->assertSame(
            ['save' => ['type' => 'module', 'url' => Pwax::url('components.badge'), 'export' => '']],
            $this->app->make(Shell::class)->runtimeConfig()['json']['actions']
        );
    }

    /**
     * Every one of these is a mistake whose only symptom is an element that renders
     * nothing, on a page that otherwise works. The doctor is where they get named.
     */
    public function test_the_doctor_names_an_entry_that_points_at_no_component(): void
    {
        $this->artisan('pwax:doctor')
            ->expectsOutputToContain('Broken')
            ->assertFailed();
    }

    public function test_the_doctor_names_a_reference_to_a_view_that_does_not_exist(): void
    {
        config()->set('pwax.json.components', ['Ghost' => "@pwaxImport('components.nope')"]);

        $this->artisan('pwax:doctor')
            ->expectsOutputToContain('components.nope')
            ->assertFailed();
    }

    public function test_the_doctor_names_an_enum_whose_values_are_not_strings(): void
    {
        config()->set('pwax.json.components', [
            'Rating' => [
                'component' => "@pwaxImport('components.badge')",
                'props' => ['stars' => ['type' => 'enum', 'values' => [1, 2, 3]]],
            ],
        ]);

        // A warning rather than a problem: the schema builder falls back to accepting any
        // string, so the page still renders. Silently, which is what this exists to fix.
        $this->artisan('pwax:doctor')->expectsOutputToContain('not all strings');
    }

    public function test_the_runtime_is_told_where_to_fetch_the_renderer(): void
    {
        $runtime = $this->app->make(Shell::class)->runtimeConfig()['json']['runtime'];

        $this->assertIsString($runtime);
        $this->assertStringContainsString('/pwax-json.js', $runtime);
        $this->assertMatchesRegularExpression(
            '/\?v=[0-9a-f]{12}$/',
            $runtime,
            'The bundle is served `immutable`, so its URL has to carry a content fingerprint '
            . 'or a returning visitor keeps the renderer they first downloaded for a year.'
        );
    }
}
