/**
 * Runtime configuration, read from a JSON island the server renders into the shell.
 *
 * Nothing in this bundle is generated by Blade. In 1.x the runtime lived inside a
 * `.blade.php` file and was assembled by string interpolation, which meant it could not
 * be linted, tested, minified as a unit, or served with a long cache lifetime. Keeping
 * every server-supplied value in one JSON block instead means this file is static.
 */

const DEFAULTS = {
    prefix: '__pwax__',
    hashRouting: false,
    serviceWorker: null,
    csrf: null,
    identity: null,
    home: '/',
};

/**
 * Read and parse a JSON script island by id.
 *
 * @param {string} id
 * @param {unknown} fallback
 */
export function readJsonIsland(id, fallback = null) {
    const el = document.getElementById(id);

    if (!el) {
        return fallback;
    }

    try {
        return JSON.parse(el.textContent || '');
    } catch (error) {
        console.error(`pwax: could not parse #${id}`, error);
        return fallback;
    }
}

/**
 * Build the runtime configuration for this page.
 */
export function loadConfig() {
    const config = { ...DEFAULTS, ...(readJsonIsland('pwax-config', {}) || {}) };

    if (!config.csrf) {
        const meta = document.querySelector('meta[name="csrf-token"]');
        config.csrf = meta ? meta.getAttribute('content') : null;
    }

    return config;
}

/**
 * The component payload the server embedded for the current URL, if any.
 *
 * Its presence is what removes the first-paint round trip: the runtime can render
 * immediately instead of fetching the page it is already on.
 */
export function loadInitialPayload() {
    return readJsonIsland('pwax-initial', null);
}
